[package]
name = "sl_cli"
description = "Easy & improved symbolic link creation"
version = "1.0.0"
authors = ["Gregory <gregory.mkv@gmail.com>"]
edition = "2018"
license = "MIT"

[[bin]]
name = "sl"
path = "src/main.rs"

[dependencies]
clap = "3.0.0-beta.1"
libc = "0.2.71"
thiserror = "1.0.19"
