name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            asset_name: sl

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable

    - uses: actions/checkout@v1

    - name: Build
      run: cargo build --release --locked

    - name: Strip binary
      run: strip target/release/sl

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/sl
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
